# Generated by Django 5.0.3 on 2024-04-06 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('product', 'size')},
        ),
    ]
